trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TerraformValidate
    displayName: "Terraform Validate Stage"
    jobs:
      - job: TerraformValidateJob
        displayName: "Terraform Validation Job"
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: "Publish Terraform Artifacts"
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              artifact: 'terraform-manifests-out'
              publishLocation: 'pipeline'

          - task: TerraformInstaller@0
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.6.0' # Ensure you use a stable version

          - script: |
              terraform init \
                -backend-config="resource_group_name=terraform-storage-rg-arup" \
                -backend-config="storage_account_name=arupbackndtffile" \
                -backend-config="container_name=tfstatefiles" \
                -backend-config="key=aks-base.tfstate"
            displayName: "Terraform Init"
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'

          - script: terraform validate
            displayName: "Terraform Validate"
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
